// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCVigIwnA8WE29PbptR2rbL1t7wGHzXY',
    appId: '1:241017123067:web:43526ca08dd8279706005e',
    messagingSenderId: '241017123067',
    projectId: 'flutter-39e38',
    authDomain: 'flutter-39e38.firebaseapp.com',
    databaseURL: 'https://flutter-39e38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-39e38.appspot.com',
    measurementId: 'G-5TTQQK5BS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANXxrNei2EL0z7Ds4UHDvt8oJfoqC4qYo',
    appId: '1:241017123067:android:970531665e32d23c06005e',
    messagingSenderId: '241017123067',
    projectId: 'flutter-39e38',
    databaseURL: 'https://flutter-39e38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-39e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXdDE1aoJ_SPgFxVxQrELFAgsDBI_phI',
    appId: '1:241017123067:ios:4a9ada719268397506005e',
    messagingSenderId: '241017123067',
    projectId: 'flutter-39e38',
    databaseURL: 'https://flutter-39e38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-39e38.appspot.com',
    iosClientId: '241017123067-etupp1a5auvhu12mm2ip9ha3f7js5lku.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXdDE1aoJ_SPgFxVxQrELFAgsDBI_phI',
    appId: '1:241017123067:ios:4a9ada719268397506005e',
    messagingSenderId: '241017123067',
    projectId: 'flutter-39e38',
    databaseURL: 'https://flutter-39e38-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-39e38.appspot.com',
    iosClientId: '241017123067-etupp1a5auvhu12mm2ip9ha3f7js5lku.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
