// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBrocmAzh85Nltnr2bcSyZX3y6WNCmgE',
    appId: '1:241017123067:web:43526ca08dd8279706005e',
    messagingSenderId: '534696389789',
    projectId: 'flutter-39e38',
    authDomain: 'flutter-39e38.firebaseapp.com',
    storageBucket: 'flutter-39e38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3gFE9Yknr31H5m6bWYCYAjzJ5ziKYak',
    appId: '1:241017123067:android:970531665e32d23c06005e',
    messagingSenderId: '534696389789',
    projectId: 'flutter-39e38',
    storageBucket: 'flutter-39e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZy_yEUs14EXbc-jjhFcasllhEz3XZXFQ',
    appId: '1:241017123067:ios:4a9ada719268397506005e',
    messagingSenderId: '534696389789',
    projectId: 'flutter-39e38',
    storageBucket: 'flutter-39e38.appspot.com',
    iosClientId: '534696389789-l95d8o95cbuh982pj89ba1cjd0cafh4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZy_yEUs14EXbc-jjhFcasllhEz3XZXFQ',
    appId: '1:241017123067:ios:4a9ada719268397506005e',
    messagingSenderId: '534696389789',
    projectId: 'flutter-39e38',
    storageBucket: 'flutter-39e38.appspot.com',
    iosClientId: '534696389789-l95d8o95cbuh982pj89ba1cjd0cafh4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
  
}
